version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=forksupdb
      - MONGO_INITDB_ROOT_USERNAME=sodabatuhan
      - MONGO_INITDB_ROOT_PASSWORD=S0DABaTuHaN
    volumes:
      - mongodb_data:/data/db
      - ./db:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: forks-up-backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-credentials.json
    volumes:
      - ./backend/src/main/resources/forks-up-firebase-adminsdk-4zto3-335c30c024.json:/app/firebase-credentials.json
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: forks-up-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    name: forks-up-network

volumes:
  mongodb_data:
