export const ingredientMap: { [key: string]: string } = {
    // Meats & Proteins
    'chicken': '🍗',
    'beef': '🥩',
    'pork': '🥓',
    'fish': '🐟',
    'salmon': '🐟',
    'tuna': '🐟',
    'turkey': '🦃',
    'lamb': '🍖',
    'meat': '🍖',
    'bacon': '🥓',
    'ham': '🍖',
    'sausage': '🌭',
    'shrimp': '🦐',
    'crab': '🦀',
    'lobster': '🦞',
    'oyster': '🦪',
    'squid': '🦑',
    'tofu': '🧊',

    // Vegetables
    'tomato': '🍅',
    'potato': '🥔',
    'carrot': '🥕',
    'corn': '🌽',
    'broccoli': '🥦',
    'cucumber': '🥒',
    'lettuce': '🥬',
    'cabbage': '🥬',
    'spinach': '🥬',
    'kale': '🥬',
    'onion': '🧅',
    'garlic': '🧄',
    'mushroom': '🍄',
    'pepper': '🫑',
    'chili': '🌶️',
    'eggplant': '🍆',
    'avocado': '🥑',
    'olive': '🫒',
    'peas': '🫛',
    'asparagus': '🥬',
    'celery': '🥬',
    'zucchini': '🥒',
    'pumpkin': '🎃',
    'radish': '🫒',
    'beetroot': '🫐',
    'artichoke': '🌱',
    'bamboo': '🎋',
    'bean': '🫘',
    'sprout': '🌱',

    // Fruits
    'apple': '🍎',
    'green apple': '🍏',
    'banana': '🍌',
    'orange': '🍊',
    'lemon': '🍋',
    'lime': '🍋',
    'strawberry': '🍓',
    'grape': '🍇',
    'watermelon': '🍉',
    'pear': '🍐',
    'peach': '🍑',
    'cherry': '🍒',
    'mango': '🥭',
    'pineapple': '🍍',
    'coconut': '🥥',
    'kiwi': '🥝',
    'blueberry': '🫐',
    'raspberry': '🫐',
    'blackberry': '🫐',
    'melon': '🍈',
    'tangerine': '🍊',
    'fig': '🫐',
    'pomegranate': '🫐',
    'dragon fruit': '🐉',

    // Dairy & Eggs
    'milk': '🥛',
    'cheese': '🧀',
    'egg': '🥚',
    'butter': '🧈',
    'cream': '🥛',
    'yogurt': '🥛',
    'ice cream': '🍨',
    'custard': '🍮',

    // Bread, Grains & Pasta
    'bread': '🍞',
    'rice': '🍚',
    'noodle': '🍜',
    'pasta': '🍝',
    'spaghetti': '🍝',
    'ramen': '🍜',
    'sandwich': '🥪',
    'bagel': '🥯',
    'pretzel': '🥨',
    'pancake': '🥞',
    'waffle': '🧇',
    'croissant': '🥐',
    'baguette': '🥖',
    'tortilla': '🫓',
    'cereal': '🥣',
    'oat': '🌾',
    'wheat': '🌾',
    'corn flour': '🌽',
    'dumpling': '🥟',
    'rice ball': '🍙',

    // Nuts & Seeds
    'peanut': '🥜',
    'nut': '🥜',
    'almond': '🥜',
    'cashew': '🥜',
    'walnut': '🥜',
    'pistachio': '🥜',
    'seed': '🌱',
    'sesame': '🌱',
    'sunflower seed': '🌱',
    'pumpkin seed': '🌱',

    // Beverages
    'coffee': '☕',
    'tea': '🫖',
    'wine': '🍷',
    'beer': '🍺',
    'juice': '🧃',
    'water': '💧',
    'cocktail': '🍸',
    'soda': '🥤',
    'champagne': '🍾',
    'sake': '🍶',

    // Sweets & Desserts
    'sugar': '🧂',
    'honey': '🍯',
    'chocolate': '🍫',
    'candy': '🍬',
    'lollipop': '🍭',
    'cookie': '🍪',
    'cake': '🍰',
    'birthday cake': '🎂',
    'pie': '🥧',
    'donut': '🍩',
    'cupcake': '🧁',
    'ice cream cone': '🍦',
    'soft ice cream': '🍦',
    'pudding': '🍮',
    'chocolate bar': '🍫',
    'popcorn': '🍿',
    'dango': '🍡',
    'moon cake': '🥮',

    // Condiments & Sauces
    'salt': '🧂',
    'oil': '🫗',
    'vinegar': '🫗',
    'sauce': '🥫',
    'ketchup': '🥫',
    'mayonnaise': '🥫',
    'mustard': '🥫',
    'soy sauce': '🫗',
    'hot sauce': '🌶️',
    'salsa': '🥫',
    'guacamole': '🥑',
    'jam': '🍯',
    'syrup': '🍯',
    'peanut butter': '🥜',

    // Herbs & Spices
    'herb': '🌿',
    'spice': '🌶️',
    'basil': '🌿',
    'oregano': '🌿',
    'thyme': '🌿',
    'rosemary': '🌿',
    'mint': '🌿',
    'parsley': '🌿',
    'cilantro': '🌿',
    'coriander': '🌿',
    'cinnamon': '🌶️',
    'ginger': '🫚',
    'turmeric': '🫚',
    'bay leaf': '🌿',
    'sage': '🌿',
    'dill': '🌿',
    'curry': '🍛',

    // Prepared Foods
    'pizza': '🍕',
    'burger': '🍔',
    'fries': '🍟',
    'hot dog': '🌭',
    'taco': '🌮',
    'burrito': '🌯',
    'sushi': '🍱',
    'bento': '🍱',
    'curry rice': '🍛',
    'soup': '🥣',
    'salad': '🥗',
    'fried rice': '🍚',
    'paella': '🥘',
    'fondue': '🫕',
    'falafel': '🧆',
    'tamale': '🫔',
};

export const getIngredientEmoji = (ingredient: string): string => {
    if (ingredient == null) {
        return '';
    }
    const lowercaseIngredient = ingredient.toLowerCase();
    for (const [key, emoji] of Object.entries(ingredientMap)) {
        if (lowercaseIngredient.includes(key)) {
            return emoji;
        }
    }
    return '';
};
