spring.application.name=forksup

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Activate dev profile by default
spring.profiles.active=dev

gemini.api.key=AIzaSyC2Blw0omBLn9etz2jd1en-EJBjyJB001M
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

## REMOTE
#spring.data.mongodb.host=138.3.251.32
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=forksupdb
#spring.data.mongodb.username=sodabatuhan
#spring.data.mongodb.password=S0DABaTuHaN
#spring.data.mongodb.authentication-database=admin

# LOCAL
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=forksupdb
spring.data.mongodb.username=sodabatuhan
spring.data.mongodb.password=S0DABaTuHaN
spring.data.mongodb.authentication-database=admin

# Dev mode settings
app.dev-mode=true
app.dev-admin-token=dev-admin-token-123

# mongodb://admin:password@localhost:27017/
# mongodb://sodabatuhan:S0DABaTuHaN@138.3.251.32:27017/