spring.application.name=forksup

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=forksupdb
spring.data.mongodb.username=admin
spring.data.mongodb.password=password
spring.data.mongodb.authentication-database=admin

# mongodb://admin:password@localhost:27017/
# mongodb://sodabatuhan:S0DABaTuHaN@138.3.251.32:27017/