spring.application.name=forksup

spring.data.mongodb.host=138.3.251.32
spring.data.mongodb.port=27017
spring.data.mongodb.database=forksupdb
spring.data.mongodb.username=sodabatuhan
spring.data.mongodb.password=S0DABaTuHaN
spring.data.mongodb.authentication-database=admin
gemini.api.key=AIzaSyC2Blw0omBLn9etz2jd1en-EJBjyJB001M
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
# mongodb://admin:password@localhost:27017/
# mongodb://sodabatuhan:S0DABaTuHaN@138.3.251.32:27017/